apiVersion: v1
kind: Service
metadata:
  name: syncthing-service
spec:
  selector:
    app: syncthing
  ports:
    - protocol: TCP
      port: 8384
      targetPort: 8384
  type: LoadBalancer
  loadBalancerIP: 192.168.1.194
