# Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
      - name: syncthing
        image: syncthing/syncthing:latest
        ports:
        - containerPort: 8384
        volumeMounts:
        - mountPath: /var/syncthing
          name: syncthing-storage
      volumes:
      - name: syncthing-storage
        persistentVolumeClaim:
          claimName: syncthing-pvc

---

# Service YAML
apiVersion: v1
kind: Service
metadata:
  name: syncthing-service
spec:
  selector:
    app: syncthing
  ports:
    - protocol: TCP
      port: 8384
      targetPort: 8384
  type: NodePort

